version: "3.8"

services:
  api-hub:
    build: .
    container_name: nexslog-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn nexslog.app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - PYTHONUNBUFFERED=1
    restart: always

  # # Interface visual r√°pida para ver os dados (Dashboard)
  # dashboard:
  #   image: curlimages/curl:latest # Placeholder para o Streamlit que faremos
  #   command: ["tail", "-f", "/dev/null"]
